export const dummyList = [
  {
    id: 1,
    img: "/imgs/1.jpg",
    title: "Title 1",
    year: "2022",
    country: ["United States of America", "United Kingdom"],
    genre: ["Drama", "Horror", "Thriller", "Adventure"],
    imdb: 5.9,
  },
  {
    id: 2,
    img: "/imgs/2.jpg",
    title: "The Shawshank Redemption",
    year: "1994",
    country: ["United States of America"],
    genre: ["Drama"],
    imdb: 9.2,
  },
  {
    id: 3,
    img: "/imgs/3.jpg",
    title: "The Godfather",
    year: "1972",
    country: ["United States of America"],
    genre: ["Crime", "Drama"],
    imdb: 9.2,
  },
  {
    id: 4,
    img: "/imgs/4.jpg",
    title: "The Dark Knight",
    year: "2008",
    country: ["United States of America", "United Kingdom"],
    genre: ["Action", "Thriller"],
    imdb: 9.0,
  },
  {
    id: 5,
    img: "/imgs/5.jpg",
    title: "12 Angry Men",
    year: "1957",
    country: ["United States of America"],
    genre: ["Drama"],
    imdb: 9.0,
  },
  {
    id: 6,
    img: "/imgs/6.jpg",
    title: "Schindler's List",
    year: "1993",
    country: ["United States of America"],
    genre: ["Biography", "Drama", "History"],
    imdb: 8.9,
  },
  {
    id: 7,
    img: "/imgs/5.jpg",
    title: "The Lord of the Rings: The Return of the King",
    year: "2003",
    country: ["New Zealand", "United States of America"],
    genre: ["Adventure", "Drama", "Fantasy"],
    imdb: 8.9,
  },
  {
    id: 8,
    img: "/imgs/4.jpg",
    title: "Pulp Fiction",
    year: "1994",
    country: ["United States of America"],
    genre: ["Crime", "Drama"],
    imdb: 8.8,
  },
  {
    id: 9,
    img: "/imgs/3.jpg",
    title: "The Good, the Bad and the Ugly",
    year: "1966",
    country: ["Italy", "Spain"],
    genre: ["Western"],
    imdb: 8.8,
  },
  {
    id: 10,
    img: "/imgs/2.jpg",
    title: "Forrest Gump",
    year: "1994",
    country: ["United States of America"],
    genre: ["Drama", "Romance"],
    imdb: 8.7,
  },
  {
    id: 11,
    img: "/imgs/1.jpg",
    title: "Inception",
    year: "2010",
    country: ["United States of America", "United Kingdom"],
    genre: ["Action", "Sci-Fi", "Thriller"],
    imdb: 8.6,
  },
];
