import { FaPlus } from "react-icons/fa6";

export const genres = () => {
  return [
    {
      label: "Action",
      value: "Action",
      icon: <FaPlus />,
    },
    {
      label: "Comedy",
      value: "Comedy",
      icon: <FaPlus />,
    },
    {
      label: "Crime",
      value: "Crime",
      icon: <FaPlus />,
    },
    {
      label: "Documentary",
      value: "Documentary",
      icon: <FaPlus />,
    },
    {
      label: "Drama",
      value: "Drama",
      icon: <FaPlus />,
    },
    {
      label: "Family",
      value: "Family",
      icon: <FaPlus />,
    },
    {
      label: "Fantasy",
      value: "Fantasy",
      icon: <FaPlus />,
    },
    {
      label: "History",
      value: "history",
      icon: <FaPlus />,
    },
    {
      label: "Horror",
      value: "horror",
      icon: <FaPlus />,
    },
    {
      label: "Thriller",
      value: "thriller",
      icon: <FaPlus />,
    },
    {
      label: "Adventure",
      value: "adventure",
      icon: <FaPlus />,
    },
    {
      label: "Science Fiction",
      value: "science_fiction",
      icon: <FaPlus />,
    },
    {
      label: "Animation",
      value: "animation",
      icon: <FaPlus />,
    },
    {
      label: "Sci-Fi & Fantasy",
      value: "sci-fi_and_fantasy",
      icon: <FaPlus />,
    },
    {
      label: "Mystery",
      value: "mystery",
      icon: <FaPlus />,
    },
    {
      label: "TV Movie",
      value: "tv_movie",
      icon: <FaPlus />,
    },
    {
      label: "Romance",
      value: "romance",
      icon: <FaPlus />,
    },
    {
      label: "Music",
      value: "music",
      icon: <FaPlus />,
    },
    {
      label: "Action & Adventure",
      value: "action_and_adventure",
      icon: <FaPlus />,
    },
    {
      label: "Western",
      value: "western",
      icon: <FaPlus />,
    },
    {
      label: "BollyWood",
      value: "bollywood",
      icon: <FaPlus />,
    },
    {
      label: "War",
      value: "war",
      icon: <FaPlus />,
    },
    {
      label: "Anime",
      value: "anime",
      icon: <FaPlus />,
    },
    {
      label: "Marvel",
      value: "marvel",
      icon: <FaPlus />,
    },
    {
      label: "War & Politics",
      value: "war_and_politics",
      icon: <FaPlus />,
    },
    {
      label: "Reality",
      value: "reality",
      icon: <FaPlus />,
    },
    {
      label: "Kids",
      value: "kids",
      icon: <FaPlus />,
    },
  ];
};

export const sortOptions = [
  {
    label: "Ascending",
    value: "asc",
    icon: <FaPlus />,
  },
  {
    label: "Descending",
    value: "desc",
    icon: <FaPlus />,
  },
  { label: "Views", value: "total_view", icon: <FaPlus /> },
  {
    label: "Rating",
    value: "rating",
    icon: <FaPlus />,
  },
  {
    label: "Release Date",
    value: "release",
    icon: <FaPlus />,
  },
  {
    label: "A-Z",
    value: "az",
    icon: <FaPlus />,
  },
  {
    label: "Z-A",
    value: "za",
    icon: <FaPlus />,
  },
];

export const countriesArray = [
  { label: "Afghanistan", value: "afghanistan", icon: <FaPlus /> },
  { label: "Albania", value: "albania", icon: <FaPlus /> },
  { label: "Algeria", value: "algeria", icon: <FaPlus /> },
  { label: "Andorra", value: "andorra", icon: <FaPlus /> },
  { label: "Angola", value: "angola", icon: <FaPlus /> },
  {
    label: "Antigua and Barbuda",
    value: "antigua_and_barbuda",
    icon: <FaPlus />,
  },
  { label: "Argentina", value: "argentina", icon: <FaPlus /> },
  { label: "Armenia", value: "armenia", icon: <FaPlus /> },
  { label: "Australia", value: "australia", icon: <FaPlus /> },
  { label: "Austria", value: "austria", icon: <FaPlus /> },
  { label: "Azerbaijan", value: "azerbaijan", icon: <FaPlus /> },
  { label: "Bahamas", value: "bahamas", icon: <FaPlus /> },
  { label: "Bahrain", value: "bahrain", icon: <FaPlus /> },
  { label: "Bangladesh", value: "bangladesh", icon: <FaPlus /> },
  { label: "Barbados", value: "barbados", icon: <FaPlus /> },
  { label: "Belarus", value: "belarus", icon: <FaPlus /> },
  { label: "Belgium", value: "belgium", icon: <FaPlus /> },
  { label: "Belize", value: "belize", icon: <FaPlus /> },
  { label: "Benin", value: "benin", icon: <FaPlus /> },
  { label: "Bhutan", value: "bhutan", icon: <FaPlus /> },
  { label: "Bolivia", value: "bolivia", icon: <FaPlus /> },
  {
    label: "Bosnia and Herzegovina",
    value: "bosnia_and_herzegovina",
    icon: <FaPlus />,
  },
  { label: "Botswana", value: "botswana", icon: <FaPlus /> },
  { label: "Brazil", value: "brazil", icon: <FaPlus /> },
  { label: "Brunei", value: "brunei", icon: <FaPlus /> },
  { label: "Bulgaria", value: "bulgaria", icon: <FaPlus /> },
  { label: "Burkina Faso", value: "burkina_faso", icon: <FaPlus /> },
  { label: "Burundi", value: "burundi", icon: <FaPlus /> },
  { label: "Cabo Verde", value: "cabo_verde", icon: <FaPlus /> },
  { label: "Cambodia", value: "cambodia", icon: <FaPlus /> },
  { label: "Cameroon", value: "cameroon", icon: <FaPlus /> },
  { label: "Canada", value: "canada", icon: <FaPlus /> },
  {
    label: "Central African Republic",
    value: "central_african_republic",
    icon: <FaPlus />,
  },
  { label: "Chad", value: "chad", icon: <FaPlus /> },
  { label: "Chile", value: "chile", icon: <FaPlus /> },
  { label: "China", value: "china", icon: <FaPlus /> },
  { label: "Colombia", value: "colombia", icon: <FaPlus /> },
  { label: "Comoros", value: "comoros", icon: <FaPlus /> },
  {
    label: "Congo (Congo-Brazzaville)",
    value: "congo_brazzaville",
    icon: <FaPlus />,
  },
  {
    label: "Congo (Congo-Kinshasa)",
    value: "congo_kinshasa",
    icon: <FaPlus />,
  },
  { label: "Costa Rica", value: "costa_rica", icon: <FaPlus /> },
  { label: "Croatia", value: "croatia", icon: <FaPlus /> },
  { label: "Cuba", value: "cuba", icon: <FaPlus /> },
  { label: "Cyprus", value: "cyprus", icon: <FaPlus /> },
  { label: "Czechia (Czech Republic)", value: "czechia", icon: <FaPlus /> },
  { label: "Denmark", value: "denmark", icon: <FaPlus /> },
  { label: "Djibouti", value: "djibouti", icon: <FaPlus /> },
  { label: "Dominica", value: "dominica", icon: <FaPlus /> },
  {
    label: "Dominican Republic",
    value: "dominican_republic",
    icon: <FaPlus />,
  },
  { label: "Ecuador", value: "ecuador", icon: <FaPlus /> },
  { label: "Egypt", value: "egypt", icon: <FaPlus /> },
  { label: "El Salvador", value: "el_salvador", icon: <FaPlus /> },
  { label: "Equatorial Guinea", value: "equatorial_guinea", icon: <FaPlus /> },
  { label: "Eritrea", value: "eritrea", icon: <FaPlus /> },
  { label: "Estonia", value: "estonia", icon: <FaPlus /> },
  { label: "Eswatini (Swaziland)", value: "eswatini", icon: <FaPlus /> },
  { label: "Ethiopia", value: "ethiopia", icon: <FaPlus /> },
  { label: "Fiji", value: "fiji", icon: <FaPlus /> },
  { label: "Finland", value: "finland", icon: <FaPlus /> },
  { label: "France", value: "france", icon: <FaPlus /> },
  { label: "Gabon", value: "gabon", icon: <FaPlus /> },
  { label: "Gambia", value: "gambia", icon: <FaPlus /> },
  { label: "Georgia", value: "georgia", icon: <FaPlus /> },
  { label: "Germany", value: "germany", icon: <FaPlus /> },
  { label: "Ghana", value: "ghana", icon: <FaPlus /> },
  { label: "Greece", value: "greece", icon: <FaPlus /> },
  { label: "Grenada", value: "grenada", icon: <FaPlus /> },
  { label: "Guatemala", value: "guatemala", icon: <FaPlus /> },
  { label: "Guinea", value: "guinea", icon: <FaPlus /> },
  { label: "Guinea-Bissau", value: "guinea_bissau", icon: <FaPlus /> },
  { label: "Guyana", value: "guyana", icon: <FaPlus /> },
  { label: "Haiti", value: "haiti", icon: <FaPlus /> },
  { label: "Honduras", value: "honduras", icon: <FaPlus /> },
  { label: "Hungary", value: "hungary", icon: <FaPlus /> },
  { label: "Iceland", value: "iceland", icon: <FaPlus /> },
  { label: "India", value: "india", icon: <FaPlus /> },
  { label: "Indonesia", value: "indonesia", icon: <FaPlus /> },
  { label: "Iran", value: "iran", icon: <FaPlus /> },
  { label: "Iraq", value: "iraq", icon: <FaPlus /> },
  { label: "Ireland", value: "ireland", icon: <FaPlus /> },
  { label: "Israel", value: "israel", icon: <FaPlus /> },
  { label: "Italy", value: "italy", icon: <FaPlus /> },
  { label: "Jamaica", value: "jamaica", icon: <FaPlus /> },
  { label: "Japan", value: "japan", icon: <FaPlus /> },
  { label: "Jordan", value: "jordan", icon: <FaPlus /> },
  { label: "Kazakhstan", value: "kazakhstan", icon: <FaPlus /> },
  { label: "Kenya", value: "kenya", icon: <FaPlus /> },
  { label: "Kiribati", value: "kiribati", icon: <FaPlus /> },
  { label: "Kuwait", value: "kuwait", icon: <FaPlus /> },
  { label: "Kyrgyzstan", value: "kyrgyzstan", icon: <FaPlus /> },
  { label: "Laos", value: "laos", icon: <FaPlus /> },
  { label: "Latvia", value: "latvia", icon: <FaPlus /> },
  { label: "Lebanon", value: "lebanon", icon: <FaPlus /> },
  { label: "Lesotho", value: "lesotho", icon: <FaPlus /> },
  { label: "Liberia", value: "liberia", icon: <FaPlus /> },
  { label: "Libya", value: "libya", icon: <FaPlus /> },
  { label: "Liechtenstein", value: "liechtenstein", icon: <FaPlus /> },
  { label: "Lithuania", value: "lithuania", icon: <FaPlus /> },
  { label: "Luxembourg", value: "luxembourg", icon: <FaPlus /> },
  { label: "Madagascar", value: "madagascar", icon: <FaPlus /> },
  { label: "Malawi", value: "malawi", icon: <FaPlus /> },
  { label: "Malaysia", value: "malaysia", icon: <FaPlus /> },
  { label: "Maldives", value: "maldives", icon: <FaPlus /> },
  { label: "Mali", value: "mali", icon: <FaPlus /> },
  { label: "Malta", value: "malta", icon: <FaPlus /> },
  { label: "Marshall Islands", value: "marshall_islands", icon: <FaPlus /> },
  { label: "Mauritania", value: "mauritania", icon: <FaPlus /> },
  { label: "Mauritius", value: "mauritius", icon: <FaPlus /> },
  { label: "Mexico", value: "mexico", icon: <FaPlus /> },
  { label: "Micronesia", value: "micronesia", icon: <FaPlus /> },
  { label: "Moldova", value: "moldova", icon: <FaPlus /> },
  { label: "Monaco", value: "monaco", icon: <FaPlus /> },
  { label: "Mongolia", value: "mongolia", icon: <FaPlus /> },
  { label: "Montenegro", value: "montenegro", icon: <FaPlus /> },
  { label: "Morocco", value: "morocco", icon: <FaPlus /> },
  { label: "Mozambique", value: "mozambique", icon: <FaPlus /> },
  { label: "Myanmar (Burma)", value: "myanmar", icon: <FaPlus /> },
  { label: "Namibia", value: "namibia", icon: <FaPlus /> },
  { label: "Nauru", value: "nauru", icon: <FaPlus /> },
  { label: "Nepal", value: "nepal", icon: <FaPlus /> },
  { label: "Netherlands", value: "netherlands", icon: <FaPlus /> },
  { label: "New Zealand", value: "new_zealand", icon: <FaPlus /> },
  { label: "Nicaragua", value: "nicaragua", icon: <FaPlus /> },
  { label: "Niger", value: "niger", icon: <FaPlus /> },
  { label: "Nigeria", value: "nigeria", icon: <FaPlus /> },
  { label: "North Korea", value: "north_korea", icon: <FaPlus /> },
  { label: "North Macedonia", value: "north_macedonia", icon: <FaPlus /> },
  { label: "Norway", value: "norway", icon: <FaPlus /> },
  { label: "Oman", value: "oman", icon: <FaPlus /> },
  { label: "Pakistan", value: "pakistan", icon: <FaPlus /> },
  { label: "Palau", value: "palau", icon: <FaPlus /> },
  { label: "Panama", value: "panama", icon: <FaPlus /> },
  { label: "Papua New Guinea", value: "papua_new_guinea", icon: <FaPlus /> },
  { label: "Paraguay", value: "paraguay", icon: <FaPlus /> },
  { label: "Peru", value: "peru", icon: <FaPlus /> },
  { label: "Philippines", value: "philippines", icon: <FaPlus /> },
  { label: "Poland", value: "poland", icon: <FaPlus /> },
  { label: "Portugal", value: "portugal", icon: <FaPlus /> },
  { label: "Qatar", value: "qatar", icon: <FaPlus /> },
  { label: "Romania", value: "romania", icon: <FaPlus /> },
  { label: "Russia", value: "russia", icon: <FaPlus /> },
  { label: "Rwanda", value: "rwanda", icon: <FaPlus /> },
  {
    label: "Saint Kitts and Nevis",
    value: "saint_kitts_and_nevis",
    icon: <FaPlus />,
  },
  { label: "Saint Lucia", value: "saint_lucia", icon: <FaPlus /> },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint_vincent_and_the_grenadines",
    icon: <FaPlus />,
  },
  { label: "Samoa", value: "samoa", icon: <FaPlus /> },
  { label: "San Marino", value: "san_marino", icon: <FaPlus /> },
  {
    label: "Sao Tome and Principe",
    value: "sao_tome_and_principe",
    icon: <FaPlus />,
  },
  { label: "Saudi Arabia", value: "saudi_arabia", icon: <FaPlus /> },
  { label: "Senegal", value: "senegal", icon: <FaPlus /> },
  { label: "Serbia", value: "serbia", icon: <FaPlus /> },
  { label: "Seychelles", value: "seychelles", icon: <FaPlus /> },
  { label: "Sierra Leone", value: "sierra_leone", icon: <FaPlus /> },
  { label: "Singapore", value: "singapore", icon: <FaPlus /> },
  { label: "Slovakia", value: "slovakia", icon: <FaPlus /> },
  { label: "Slovenia", value: "slovenia", icon: <FaPlus /> },
  { label: "Solomon Islands", value: "solomon_islands", icon: <FaPlus /> },
  { label: "Somalia", value: "somalia", icon: <FaPlus /> },
  { label: "South Africa", value: "south_africa", icon: <FaPlus /> },
  { label: "South Korea", value: "south_korea", icon: <FaPlus /> },
  { label: "South Sudan", value: "south_sudan", icon: <FaPlus /> },
  { label: "Spain", value: "spain", icon: <FaPlus /> },
  { label: "Sri Lanka", value: "sri_lanka", icon: <FaPlus /> },
  { label: "Sudan", value: "sudan", icon: <FaPlus /> },
  { label: "Suriname", value: "suriname", icon: <FaPlus /> },
  { label: "Sweden", value: "sweden", icon: <FaPlus /> },
  { label: "Switzerland", value: "switzerland", icon: <FaPlus /> },
  { label: "Syria", value: "syria", icon: <FaPlus /> },
  { label: "Taiwan", value: "taiwan", icon: <FaPlus /> },
  { label: "Tajikistan", value: "tajikistan", icon: <FaPlus /> },
  { label: "Tanzania", value: "tanzania", icon: <FaPlus /> },
  { label: "Thailand", value: "thailand", icon: <FaPlus /> },
  { label: "Timor-Leste", value: "timor_leste", icon: <FaPlus /> },
  { label: "Togo", value: "togo", icon: <FaPlus /> },
  { label: "Tonga", value: "tonga", icon: <FaPlus /> },
  {
    label: "Trinidad and Tobago",
    value: "trinidad_and_tobago",
    icon: <FaPlus />,
  },
  { label: "Tunisia", value: "tunisia", icon: <FaPlus /> },
  { label: "Turkey", value: "turkey", icon: <FaPlus /> },
  { label: "Turkmenistan", value: "turkmenistan", icon: <FaPlus /> },
  { label: "Tuvalu", value: "tuvalu", icon: <FaPlus /> },
  { label: "Uganda", value: "uganda", icon: <FaPlus /> },
  { label: "Ukraine", value: "ukraine", icon: <FaPlus /> },
  {
    label: "United Arab Emirates",
    value: "united_arab_emirates",
    icon: <FaPlus />,
  },
  { label: "United Kingdom", value: "united_kingdom", icon: <FaPlus /> },
  {
    label: "United States of America",
    value: "united_states_of_america",
    icon: <FaPlus />,
  },
  { label: "Uruguay", value: "uruguay", icon: <FaPlus /> },
  { label: "Uzbekistan", value: "uzbekistan", icon: <FaPlus /> },
  { label: "Vanuatu", value: "vanuatu", icon: <FaPlus /> },
  { label: "Vatican City", value: "vatican_city", icon: <FaPlus /> },
  { label: "Venezuela", value: "venezuela", icon: <FaPlus /> },
  { label: "Vietnam", value: "vietnam", icon: <FaPlus /> },
  { label: "Yemen", value: "yemen", icon: <FaPlus /> },
  { label: "Zambia", value: "zambia", icon: <FaPlus /> },
  { label: "Zimbabwe", value: "zimbabwe", icon: <FaPlus /> },
];

export const aToZ = [
  {
    label: "0-9",
    key: "number",
  },
  {
    label: "A",
    key: "a",
  },
  {
    label: "B",
    key: "b",
  },
  {
    label: "C",
    key: "c",
  },
  {
    label: "D",
    key: "d",
  },
  {
    label: "E",
    key: "e",
  },
  {
    label: "F",
    key: "f",
  },
  {
    label: "G",
    key: "g",
  },
  {
    label: "H",
    key: "h",
  },
  {
    label: "I",
    key: "i",
  },
  {
    label: "J",
    key: "j",
  },
  {
    label: "K",
    key: "k",
  },
  {
    label: "L",
    key: "l",
  },
  {
    label: "M",
    key: "m",
  },
  {
    label: "N",
    key: "n",
  },
  {
    label: "O",
    key: "o",
  },
  {
    label: "P",
    key: "p",
  },
  {
    label: "Q",
    key: "q",
  },
  {
    label: "R",
    key: "r",
  },
  {
    label: "S",
    key: "s",
  },
  {
    label: "T",
    key: "t",
  },
  {
    label: "U",
    key: "u",
  },
  {
    label: "V",
    key: "v",
  },
  {
    label: "W",
    key: "w",
  },
  {
    label: "X",
    key: "x",
  },
  {
    label: "Y",
    key: "y",
  },
  {
    label: "Z",
    key: "z",
  },
];
